[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
itertools = "0.14.0"
strum = "0.27.1"
strum_macros = "0.27.1"
